[tools]
bat = "latest"
btop = "latest"
carapace = "latest"
fd = "latest"
fzf = "latest"
ghcup = "latest"
github-cli = "latest"
gron = "latest"
jq = "latest"
jqp = "latest"
lazyssh = "latest"
lsd = "latest"
lua = "latest"
mongosh = "latest"
neovim = "latest"
node = "lts"
ollama = "latest"
opencode = "latest"
pnpm = "latest"
resvg = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
watchexec = "latest"
yarn = "latest"
yazi = "latest"
yq = "latest"
zoxide = "latest"

[env]
MISE_COLOR_THEME = "catppuccin"
